
export function generateCubeStl(size: number): Blob {
    const halfSize = size / 2;
    // Vertices of a cube centered at origin
    //    v6----- v5
    //   /|      /|
    //  v1------v0|
    //  | |     | |
    //  | |v7---|-|v4
    //  |/      |/
    //  v2------v3

    const vertices = [
        [halfSize, halfSize, halfSize],    // v0
        [-halfSize, halfSize, halfSize],   // v1
        [-halfSize, -halfSize, halfSize],  // v2
        [halfSize, -halfSize, halfSize],   // v3
        [halfSize, -halfSize, -halfSize],  // v4
        [halfSize, halfSize, -halfSize],   // v5
        [-halfSize, halfSize, -halfSize],  // v6
        [-halfSize, -halfSize, -halfSize], // v7
    ];

    // Faces (CCW winding for outside normal)
    // Each face is 2 triangles
    const indices = [
        // Front (v0, v1, v2, v3) -> 0,1,2, 0,2,3
        [0, 1, 2], [0, 2, 3],
        // Back (v5, v6, v7, v4) -> 5,4,7, 5,7,6
        [5, 4, 7], [5, 7, 6],
        // Top (v0, v5, v6, v1) -> 0,5,6, 0,6,1
        [0, 5, 6], [0, 6, 1],
        // Bottom (v3, v2, v7, v4) -> 3,2,7, 3,7,4
        [3, 2, 7], [3, 7, 4],
        // Right (v0, v3, v4, v5) -> 0,3,4, 0,4,5
        [0, 3, 4], [0, 4, 5],
        // Left (v1, v6, v7, v2) -> 1,6,7, 1,7,2
        [1, 6, 7], [1, 7, 2]
    ];

    return createStlBlob(vertices, indices);
}

export function generateCylinderStl(radius: number, height: number, segments: number): Blob {
    const vertices: number[][] = [];
    const indices: number[][] = [];

    const halfHeight = height / 2;

    // Generate vertices
    // Top center: index 0
    vertices.push([0, halfHeight, 0]);
    // Bottom center: index 1
    vertices.push([0, -halfHeight, 0]);

    // Top rim vertices: indices 2 to 2+segments-1
    for (let i = 0; i < segments; i++) {
        const angle = (i / segments) * Math.PI * 2;
        vertices.push([Math.cos(angle) * radius, halfHeight, Math.sin(angle) * radius]);
    }

    // Bottom rim vertices: indices 2+segments to 2+2*segments-1
    for (let i = 0; i < segments; i++) {
        const angle = (i / segments) * Math.PI * 2;
        vertices.push([Math.cos(angle) * radius, -halfHeight, Math.sin(angle) * radius]);
    }

    const topCenterIdx = 0;
    const bottomCenterIdx = 1;
    const topStartIdx = 2;
    const bottomStartIdx = 2 + segments;

    for (let i = 0; i < segments; i++) {
        const next = (i + 1) % segments;

        // Top Cap (CCW relative to top)
        // Center, Rim_i, Rim_next
        // Normal facing up: (0, 1, 0)
        indices.push([topCenterIdx, topStartIdx + i, topStartIdx + next]);

        // Bottom Cap (CW relative to top, so CCW relative to outside)
        // Center, Rim_next, Rim_i
        // Normal facing down: (0, -1, 0)
        indices.push([bottomCenterIdx, bottomStartIdx + next, bottomStartIdx + i]);

        // Side Quads (2 triangles)
        // Top_i, Bottom_i, Bottom_next
        // Top_i, Bottom_next, Top_next
        const t_i = topStartIdx + i;
        const t_n = topStartIdx + next;
        const b_i = bottomStartIdx + i;
        const b_n = bottomStartIdx + next;

        indices.push([t_i, b_i, b_n]);
        indices.push([t_i, b_n, t_n]);
    }

    return createStlBlob(vertices, indices);
}

function createStlBlob(vertices: number[][], indices: number[][]): Blob {
    const triangleCount = indices.length;
    // Header: 80 bytes
    // Count: 4 bytes
    // Triangles: 50 * triangleCount bytes
    const bufferLength = 80 + 4 + (50 * triangleCount);
    const buffer = new ArrayBuffer(bufferLength);
    const view = new DataView(buffer);

    // Offset
    let offset = 0;

    // Header (skip, default 0s is fine, or put a string)
    // "Binary STL generated by shapeGenerators.ts"
    const header = "Binary STL generated by shapeGenerators.ts";
    for (let i = 0; i < Math.min(header.length, 80); i++) {
        view.setUint8(i, header.charCodeAt(i));
    }
    offset += 80;

    // Triangle Count
    view.setUint32(offset, triangleCount, true); // Little endian
    offset += 4;

    // Triangles
    for (let i = 0; i < triangleCount; i++) {
        const idx = indices[i];
        const v1 = vertices[idx[0]];
        const v2 = vertices[idx[1]];
        const v3 = vertices[idx[2]];

        // Normal (0,0,0) - let viewer calculate or compute simple face normal
        // Normal calculation:
        // U = v2 - v1, V = v3 - v1
        // Nx = UyVz - UzVy
        // Ny = UzVx - UxVz
        // Nz = UxVy - UyVx

        const u = [v2[0] - v1[0], v2[1] - v1[1], v2[2] - v1[2]];
        const v = [v3[0] - v1[0], v3[1] - v1[1], v3[2] - v1[2]];

        let nx = u[1] * v[2] - u[2] * v[1];
        let ny = u[2] * v[0] - u[0] * v[2];
        let nz = u[0] * v[1] - u[1] * v[0];

        const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
        if (len > 0) {
            nx /= len; ny /= len; nz /= len;
        }

        view.setFloat32(offset, nx, true); offset += 4;
        view.setFloat32(offset, ny, true); offset += 4;
        view.setFloat32(offset, nz, true); offset += 4;

        // V1
        view.setFloat32(offset, v1[0], true); offset += 4;
        view.setFloat32(offset, v1[1], true); offset += 4;
        view.setFloat32(offset, v1[2], true); offset += 4;

        // V2
        view.setFloat32(offset, v2[0], true); offset += 4;
        view.setFloat32(offset, v2[1], true); offset += 4;
        view.setFloat32(offset, v2[2], true); offset += 4;

        // V3
        view.setFloat32(offset, v3[0], true); offset += 4;
        view.setFloat32(offset, v3[1], true); offset += 4;
        view.setFloat32(offset, v3[2], true); offset += 4;

        // Attribute byte count
        view.setUint16(offset, 0, true); offset += 2;
    }

    return new Blob([buffer], { type: 'application/octet-stream' });
}
